### PR TITLE
Attempting to fix https://github.com/concourse/concourse-lite/issues/9

### PR DESCRIPTION
**Pull request by miroswan**
Reference:

https://www.virtualbox.org/manual/ch08.html

### CODE REVIEW

**Comment by vito** [comment]
Given https://github.com/concourse/concourse-lite/issues/9#issuecomment-249642605 - have you been able to test this? I think you'd need to build with VirtualBox 5.1.x and try running it with VirtualBox 5.0.x. to confirm.

**Comment by miroswan** [comment]
@vito The strange thing is that when I build it via Packer prior to the changes I didn't have the problem. It was when I retrieve the box from atlas using the instructions on the site. I'll make sure I have the versions specified above and test locally.

**Comment by miroswan** [comment]
I'll also try upgrading my VB and Vagrant and see if I still see the problem at all without any change.

**Comment by miroswan** [comment]
@vito I've confirmed that upgrading VB fixes the issue without the suggested modification here. I'd be happy with closing the PR.

**Comment by vito** [comment]
It seems like a reasonable change if it makes things work with 5.0.x. A lot of people ran into this.

**Comment by vito** [comment]
On second thought the consensus seems to be that it's a VirtualBox regression, so I'm not sure how I feel about checking in a workaround that they may just fix anyway. At least upgrading works and these issues have documented how to get things going (either upgrade VirtualBox or add that workaround).

Thanks!

**Pull request closed without merging**
