### PR TITLE
Remove hardcoded 192.168.100.4 IP address

### PR DESCRIPTION
**Pull request by jwiebalk**
I'd like to propose changing the hardcoded `192.168.100.4` address into something that detects the current IP address automatically.

This was my implementation using `ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`.

It properly detects the current `eth0` IP address and places it in the .conf files for the web/worker processes.

I use Vagrant with bridging so this allows the RedirectURI to be formatted properly for using OAuth.

### CODE REVIEW

**Comment by vito** [comment]
Is it guaranteed to be `eth0`? If not this may be a decent approach:

https://github.com/concourse/concourse/blob/master/dev/util/external-ip#L4

**Comment by jwiebalk** [comment]
I reworked this a bit. Switched to the `ip route` logic and moved it to set an env variable.

This should make it easier to read and also allows for a "fallback" to the `192.168.100.4` address if the ip route command fails or is unable to determine the correct address.

@vito 💭 ?

**Comment by vito** [comment]
Looks good, thanks!

**Comment by vito** [comment]
I ended up having to revert this; it was picking a `10.x.x.x` address instead of the intended `192.168.100.4` address.

**Pull request merged**
